(require 'color-theme)

(defconst tango-butter1 "#fce94f")
(defconst tango-butter2 "#edd400")
(defconst tango-butter3 "#c4a000")

(defconst tango-orange1 "#fcaf3e")
(defconst tango-orange2 "#f57900")
(defconst tango-orange3 "#ce5c00")

(defconst tango-chocolate1 "#e9b96e")
(defconst tango-chocolate2 "#c17d11")
(defconst tango-chocolate3 "#8f5902")

(defconst tango-chameleon1 "#8ae234")
(defconst tango-chameleon2 "#73d216")
(defconst tango-chameleon3 "#4e9a06")

(defconst tango-skyblue1 "#729fcf")
(defconst tango-skyblue2 "#3465a4")
(defconst tango-skyblue3 "#204a87")

(defconst tango-plum1 "#ad7fa8")
(defconst tango-plum2 "#75507b")
(defconst tango-plum3 "#5c3566")

(defconst tango-scarlet-red1 "#ef2929")
(defconst tango-scarlet-red2 "#cc0000")
(defconst tango-scarlet-red3 "#a40000")

(defconst tango-aluminium1 "#eeeeec")
(defconst tango-aluminium2 "#d3d7cf")
(defconst tango-aluminium3 "#babdb6")

(defconst tango-aluminium4 "#888a85")
(defconst tango-aluminium5 "#555753")
(defconst tango-aluminium6 "#2e3436")

(defun color-theme-tango+ ()
  "A color theme based on Tango Palette."
  (interactive)
  (color-theme-install
   `(color-theme-tango+

     ((background-color . ,tango-aluminium6)
      (background-mode  .  dark)
      (border-color     . ,tango-aluminium4)
      (cursor-color     . ,tango-butter1)
      (foreground-color . ,tango-aluminium2))

     (bold                                   ((t (:weight bold))))
     (bold-italic                            ((t (:inherit bold :inherit italic))))
     (border                                 ((t (:foreground ,tango-aluminium2))))
     (button                                 ((t (:inherit link))))
     (custom-button                          ((t (:background ,tango-aluminium5 :box (:line-width 1 :style released-button)))))
     (custom-button-mouse                    ((t (:inherit custom-button :box (:line-width 1 :style released-button)))))
     (custom-button-pressed                  ((t (:inherit custom-button :box (:line-width 1 :style pressed-button)))))
     (custom-button-pressed-unraised         ((t (:inherit custom-button :box (:line-width 1 :style pressed-button)))))
     (custom-button-unraised                 ((t (:inherit custom-button :box (:line-width 1 :style released-button)))))
     (custom-state                           ((t (:inherit default))))
     (custom-variable-tag                    ((t (:foreground ,tango-skyblue1 :weight bold))))
     (default                                ((t (:foreground ,tango-aluminium2))))
     (escape-glyph                           ((t (:foreground ,tango-scarlet-red3 :background ,tango-aluminium2 :weight bold))))
     (fixed-pitch                            ((t (nil))))

     (comint-highlight-prompt                ((t (:foreground ,tango-chameleon2))))
     (comint-highlight-input                 ((t (nil))))

     (cperl-array-face                       ((t (:foreground ,tango-chocolate1 :weight bold))))
     (cperl-hash-face                        ((t (:foreground ,tango-orange3 :weight bold))))
     (cperl-nonoverridable-face              ((t (:foreground ,tango-chameleon1 :weight bold))))

     (font-lock-builtin-face                 ((t (:foreground ,tango-skyblue1))))
     (font-lock-comment-delimiter-face       ((t (:inherit font-lock-comment-face))))
     (font-lock-comment-face                 ((t (:foreground ,tango-aluminium4))))
     (font-lock-constant-face                ((t (:foreground ,tango-chameleon1))))
     (font-lock-doc-face                     ((t (:foreground ,tango-aluminium4))))
     (font-lock-function-name-face           ((t (:foreground ,tango-butter1 :weight bold))))
     (font-lock-keyword-face                 ((t (:foreground ,tango-skyblue1 :weight bold))))
     (font-lock-negation-char-face           ((t (:foreground ,tango-scarlet-red1 :weight bold))))
     (font-lock-preprocessor-face            ((t (:foreground ,tango-orange3))))
     (font-lock-string-face                  ((t (:foreground ,tango-plum1))))
     (font-lock-type-face                    ((t (:foreground ,tango-chameleon1 :bold f))))
     (font-lock-variable-name-face           ((t (:inherit default :weight bold))))
     (font-lock-warning-face                 ((t (:foreground ,tango-orange2 :weight bold))))

     (fringe                                 ((t (:background ,tango-aluminium6))))
     (header-line                            ((t (:weight bold :underline ,tango-aluminium2))))
     (highlight                              ((t (:background ,tango-aluminium5 ))))

     (ido-first-match                        ((t (:weight bold))))
     (ido-only-match                         ((t (:foreground ,tango-chameleon1 :weight bold))))
     (ido-subdir                             ((t (:foreground ,tango-plum1))))
     (ido-incomplete-regexp                  ((t (:inherit font-lock-warning-face))))
     (ido-indicator                          ((t (:foreground ,tango-scarlet-red1 :weight bold))))

     (info-header-node                       ((t (:weight bold))))
     (info-menu-header                       ((t (:weight bold))))
     (info-menu-star                         ((t (:foreground ,tango-scarlet-red1 :weight bold))))
     (info-node                              ((t (:weight bold))))
     (info-title-4                           ((t (:weight bold))))
     (info-xref                              ((t (:foreground ,tango-skyblue1))))
     (info-xref-visited                      ((t (:foreground ,tango-plum1))))

     (isearch                                ((t (:foreground ,tango-aluminium6 :background ,tango-orange2))))
     (isearch-lazy-highlight-face            ((t (:foreground ,tango-aluminium6 :background ,tango-chocolate1))))
     (lazy-highlight                         ((t (:foreground ,tango-chocolate1))))
     (link                                   ((t (:foreground ,tango-skyblue1 :underline t))))
     (link-visited                           ((t (:foreground ,tango-plum1 :underline t))))
     (match                                  ((t (:foreground ,tango-chameleon1 :weight bold))))
     (minibuffer-prompt                      ((t (:foreground ,tango-skyblue1 :weight bold))))
     (mode-line                              ((t (:foreground ,tango-aluminium6 :background ,tango-skyblue1 :weight bold ))))
     (mode-line-buffer-id                    ((t (:weight bold))))
     (mode-line-highlight                    ((t (nil))))
     (mode-line-inactive                     ((t (:foreground ,tango-aluminium2 :background ,tango-aluminium5 :weight bold))))
     (region                                 ((t (:background ,tango-aluminium5))))
     (scroll-bar                             ((t (nil))))
     (secondary-selection                    ((t (:background ,tango-plum3))))
     (shadow                                 ((t (:foreground ,tango-aluminium3))))
     (show-paren-match-face                  ((t (:foreground ,tango-aluminium6 :background ,tango-chameleon2))))
     (show-paren-mismatch-face               ((t (:foreground ,tango-aluminium6 :background ,tango-plum1))))
     (tool-bar                               ((t (nil))))
     (tooltip                                ((t (:foreground ,tango-aluminium6 :background ,tango-aluminium2))))
     (trailing-whitespace                    ((t (nil))))
     (underline                              ((t (:underline t))))
     (variable-pitch                         ((t (nil))))
     (vertical-border                        ((t (:inherit border))))
     (widget-button                          ((t (:inherit custom-button))))
     (widget-button-pressed                  ((t (:inherit custom-button-pressed))))
     (widget-documentation                   ((t (:foreground ,tango-chameleon3))))
     (widget-field                           ((t (:background ,tango-aluminium5))))
     (widget-single-line-field               ((t (:background ,tango-aluminium5))))

     (speedbar-button-face                   ((t (:foreground ,tango-aluminium2 :weight bold))))
     (speedbar-directory-face                ((t (:foreground ,tango-chameleon1 :weight bold))))
     (speedbar-file-face                     ((t (:foreground ,tango-skyblue1))))
     (speedbar-highlight-face                ((t (:underline t))))
     (speedbar-selected-face                 ((t (:weight bold))))
     (speedbar-separator-face                ((t (:inherit mode-line))))
     (speedbar-tag-face                      ((t (nil))))

     (makefile-makepp-perl                   ((t (:foreground ,tango-skyblue1 :background ,tango-aluminium6))))
     (makefile-space                         ((t (:background ,tango-aluminium5))))

     (font-latex-bold-face                   ((t (:inherit bold))))
     (font-latex-doctex-documentation-face   ((t (:background ,tango-aluminium5))))
     (font-latex-italic-face                 ((t (:inherit italic))))
     (font-latex-math-face                   ((t (nil))))
     (font-latex-sectioning-5-face           ((t (:foreground ,tango-plum1 :weight bold))))
     (font-latex-sedate-face                 ((t (:foreground ,tango-skyblue1))))
     (font-latex-slide-title-face            ((t (:inherit font-latex-sectioning-0-face))))
     (font-latex-string-face                 ((t (:inherit font-lock-string-face))))
     (font-latex-subscript-face              ((t (:height 0.8))))
     (font-latex-superscript-face            ((t (:height 0.8))))
     (font-latex-verbatim-face               ((t (:inherit default))))
     (font-latex-warning-face                ((t (:foreground ,tango-orange2 :weight bold))))
     (preview-face                           ((t (nil))))
     (preview-reference-face                 ((t (nil))))

     ;; (buffer-menu-buffer                  ((t (nil))))
     ;; (c-nonbreakable-space-face           ((t (nil))))
     ;; (completions-common-part             ((t (nil))))
     ;; (completions-first-difference        ((t (nil))))
     ;; (cursor                              ((t (nil))))
     ;; (custom-changed                      ((t (nil))))
     ;; (custom-comment                      ((t (nil))))
     ;; (custom-comment-tag                  ((t (nil))))
     ;; (custom-documentation                ((t (nil))))
     ;; (custom-face-tag                     ((t (nil))))
     ;; (custom-group-tag                    ((t (nil))))
     ;; (custom-group-tag-1                  ((t (nil))))
     ;; (custom-invalid                      ((t (nil))))
     ;; (custom-link                         ((t (nil))))
     ;; (custom-modified                     ((t (nil))))
     ;; (custom-rogue                        ((t (nil))))
     ;; (custom-saved                        ((t (nil))))
     ;; (custom-set                          ((t (nil))))
     ;; (custom-themed                       ((t (nil))))
     ;; (custom-variable-button              ((t (nil))))
     ;; (file-name-shadow                    ((t (nil))))
     ;; (font-lock-regexp-grouping-backslash ((t (nil))))
     ;; (font-lock-regexp-grouping-construct ((t (nil))))
     ;; (help-argument-name                  ((t (nil))))
     ;; (info-header-xref                    ((t (nil))))
     ;; (info-title-1                        ((t (nil))))
     ;; (info-title-2                        ((t (nil))))
     ;; (info-title-3                        ((t (nil))))

     ;; (menu                                ((t (nil))))
     ;; (mouse                               ((t (nil))))
     ;; (next-error                          ((t (nil))))
     ;; (nobreak-space                       ((t (nil))))
     ;; (query-replace                       ((t (nil))))
     ;; (widget-inactive                     ((t (nil))))

     ;; (prolog-builtin-face                 ((t (nil))))
     ;; (prolog-exception-face               ((t (nil))))
     ;; (prolog-exit-face                    ((t (nil))))
     ;; (prolog-redo-face                    ((t (nil))))
     ;; (prolog-warning-face                 ((t (nil))))

     ;; (compilation-column-number           ((t (nil))))
     ;; (compilation-error                   ((t (nil))))
     ;; (compilation-info                    ((t (nil))))
     ;; (compilation-line-number             ((t (nil))))
     ;; (compilation-warning                 ((t (nil))))
     )))

(provide 'tango+)

